### ISSUE TITLE
src_dir_name ignored

### ISSUE THREAD

**Issue by horvathp** [benjmarshall/hlsclt#15]
The recent changes trigger a small omission in the build steps. Apparently, 
do_end_build_stuff() assumes that the source files are in src/ instead of using the src_dir_name configuration setting.

See this (src_dir_name = "." was specified in the hls_config.py)

Copying the source and config files to solution1
Traceback (most recent call last):
  File "/usr/local/bin/hlsclt", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1093, in invoke
    return _process_result(rv)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1031, in _process_result
    **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hlsclt/build_commands/build_commands.py", line 164, in build_end_callback
    do_end_build_stuff(ctx,sub_command_returns,report)
  File "/usr/local/lib/python2.7/dist-packages/hlsclt/build_commands/build_commands.py", line 122, in do_end_build_stuff
    shutil.copytree("src", destiny_src)
  File "/usr/lib/python2.7/shutil.py", line 171, in copytree
    names = os.listdir(src)
OSError: [Errno 2] No such file or directory: 'src'

Ubuntu 16.04, HLS 2018.3

**Comment by benjmarshall** [comment]
Good catch, I'll push a change to make sure the backup feature respects the config file asap.

**Comment by benjmarshall** [comment]
Hi, I have created a PR (#18) to fix this issue, I can't test this just at the moment but it's a very small change so should work. Can you update to that branch and test if this fixes your issue?
Thanks, Ben

**Comment by horvathp** [comment]
Hi, I hope I didn't mess up the versions, but it does not seem to work:
  File "build/bdist.linux-x86_64/egg/hlsclt/build_commands/build_commands.py", line 164, in build_end_callback
  File "build/bdist.linux-x86_64/egg/hlsclt/build_commands/build_commands.py", line 122, in do_end_build_stuff
  File "/usr/lib/python2.7/shutil.py", line 171, in copytree
    names = os.listdir(src)
OSError: [Errno 2] No such file or directory: 'src'

BTW the package calls itself hlsclt1.0.0.a6, but it should be called hlsclt1.0.0a6 (the installer normalizes this at some point, but seemingly not everywhere)
Moreover, I'm unable to install the package with
python setup.py install
That installs the egg file but nothing else.

**Comment by benjmarshall** [comment]
My bad, I only put in 1 of the 2 required changes! Apologies, I'm doing this on mobile while I have some free time. Can you try it again for me?

I'll look into the version thing separately.

**Comment by horvathp** [comment]
Hi Ben,
many thanks for dealing with this issue. The previous error is fixed, however, something terrible is happening, as if the backup would happen recursively. I'm not sure what is the expected outcome, what is this operation supposed to accomplish but I'm afraid something goes horribly wrong if all the sources are in the current directory instead of their own subdirectory. (Which I personally prefer, for most projects consist only of 3 source files and I don't see the point having separate folders for them)

**Comment by benjmarshall** [comment]
Can you write down exactly what you're directory structure is? And copy the text in from your config file?

**Comment by horvathp** [comment]
If I turn a conformist and place the sources under a non-standard subdirecture, such as srcs/, it works.
(Doing so I realized that when compiling the testbench, the include directory does not get added to the include path. I.e., I need to specify the relative path to my include file, that is, if the structure is
src/mod.h
src/mod.cpp
tb/mod_tb.cpp,
I need to say
#include "../src/mod.h"
which is unfortunate. 
Is this by design?

**Comment by horvathp** [comment]
OK, so what triggers the recursive disaster is the following:
src_dir_name = "."
tb_dir_name = "."
src_files = ["spectrum_post.h","spectrum_post.cpp"]
tb_files = ["spectrum_post_tb.cpp"]
which used to work perfectly (everything in the same folder, including hls_config.py)
Now the new feature probably tries to copy the entire contents of the "src" folder somewhere under solution1. But if src_dir_name is"." , solution1 itself is within the "src" folder, and bingo. 

More generally, if one has to specify the source files separately, not only the folder that contains them, one would expect that the tool manages the source files separately. That is, contents of the current "src" folder are not equivalent to the set of source files. I.e., copying the folder itself instead of copying the source files listed in the config file is incorrect behavior. If the "src" folder contains some other garbage, that would be backed up as well, which is again not expected.

**Comment by benjmarshall** [comment]
Ahh OK, I see what is happening. I have never considered have all source under the top level folder. I typically deal with much larger projects where separation of source and testbench is important enough to warrant distinct directories.

I appreciate the confusion about managing of source files, directories vs files. This is a bit of a hang up from how the tool was originally developed (quickly and aligned with may way of working). I agree this should be looked at to see if a more sensible system can be settled on. 

For now there are two short term options to resolve this. You can continue to use a dedicated source folder, or we can add a flag to enable/disable the source backup feature which will get around this recursive copy.

**Comment by horvathp** [comment]
Ben,
I understand that I abused your tool :) I'd move on and use it the way it is intended but it would be then very handy if the "src" folder was implicitly added to the include search path for the testbench.
I can circumhack this by specifying
cflags = "-I../../../../src"
in hls_config.py, but I think it seems logical to be able to reference the project-specific includes without specifying the (relative or absolute) path to them in the testbench C source.

Thanks again for your work.
Peter

**Comment by benjmarshall** [comment]
Thanks Peter. I'm going to close this issue for now and will merge the changes from #18 into develop.

I'm going to open a new issue to continue discussion on how better to manage source files and I'd like your further input on this to build towards something that makes sense to various users whilst not making the tool onerously complex.
