### ISSUE TITLE
how to add link library into hls_config.py

### ISSUE THREAD

**Issue by 3togo** [benjmarshall/hlsclt#16]
how to translate the following into hls_config.py 
add_files -tb tb/xxx.c -cflags -lnetpbm

**Comment by 3togo** [comment]
how to add linker flags
![screenshot from 2019-02-01 20-56-43](https://user-images.githubusercontent.com/731338/52124390-0260e380-2664-11e9-8a3d-9a8091fbd479.png)

**Comment by benjmarshall** [comment]
Hi, you should be able to add entries for the cflaga option in your hls_config.py.

In this case it would be: cflags = "-lnetbpm"

I can't test this right now, could you let me know if this works for you? If not I can look into into it further!

**Comment by 3togo** [comment]
it will only add cflags for files in src directories but not those in testbench directory

**Comment by benjmarshall** [comment]
Ah yes, you are right, I had missed that detail in your original post. It looks like you have added some changes to your PR (#17) which might add the functionality you are talking about here, is that correct?
